import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'currency', type: 'string' },
        { name: 'balance', type: 'number' },
        { name: 'initial_balance', type: 'number' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'date', type: 'number', isIndexed: true },
        { name: 'category_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'tags', type: 'string' }, // JSON
        { name: 'recurring', type: 'boolean' },
        { name: 'recurring_id', type: 'string', isOptional: true },
        { name: 'attachments', type: 'string' }, // JSON
        { name: 'destination_account_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'parent_id', type: 'string', isOptional: true },
        { name: 'is_default', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'budgets',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'period', type: 'string' },
        { name: 'start_date', type: 'number' },
        { name: 'end_date', type: 'number', isOptional: true },
        { name: 'spent', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'portfolio_assets',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'symbol', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'quantity', type: 'number' },
        { name: 'average_cost', type: 'number' },
        { name: 'current_price', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'market_value', type: 'number' },
        { name: 'total_cost', type: 'number' },
        { name: 'gain_loss', type: 'number' },
        { name: 'gain_loss_percentage', type: 'number' },
        { name: 'last_price_update', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'portfolio_transactions',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'asset_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'quantity', type: 'number' },
        { name: 'price', type: 'number' },
        { name: 'fees', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'date', type: 'number', isIndexed: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
  ],
});
